// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAruZNVq4gKZYjgEuFfdB3BmD6vlM1lc6k',
    appId: '1:96304314724:web:ce151e343be6165dfea271',
    messagingSenderId: '96304314724',
    projectId: 'flutter-fire-pos',
    authDomain: 'flutter-fire-pos.firebaseapp.com',
    storageBucket: 'flutter-fire-pos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHK0qj1jGEQRgM6zgtL5tPAcydAH_r2c',
    appId: '1:96304314724:android:016d875441aee1d3fea271',
    messagingSenderId: '96304314724',
    projectId: 'flutter-fire-pos',
    storageBucket: 'flutter-fire-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBX6TwSI0U6FpVc3zQpz0Xm_AoP5fV0Kk',
    appId: '1:96304314724:ios:8411fd921621a86afea271',
    messagingSenderId: '96304314724',
    projectId: 'flutter-fire-pos',
    storageBucket: 'flutter-fire-pos.appspot.com',
    iosClientId: '96304314724-3q814v2hl4ge15afmcg5a2n5dejdgr4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBX6TwSI0U6FpVc3zQpz0Xm_AoP5fV0Kk',
    appId: '1:96304314724:ios:9e1c30dac8a48446fea271',
    messagingSenderId: '96304314724',
    projectId: 'flutter-fire-pos',
    storageBucket: 'flutter-fire-pos.appspot.com',
    iosClientId: '96304314724-j29mtbs1l80a9vk5o6np8q4ujfjtlc7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirePos.RunnerTests',
  );
}
